feat: add files
SiarheiBalt/Server pull request #1
Opened 2021-10-25 06:16 UTC by SiarheiBalt

2021-10-25 10:33 UTC, Aliaksandrlosich requested changes

2021-10-25 10:33 UTC, Aliaksandrlosich commented on routes/auth.routes.js
> +      res.status(201).json({ message: 'Пользователь создан' });
Лучше все res сгруппировать в один,  особенно если позволяет реализация. Условно один вход/выход. Так проще и отлаживать, и понимать что происходит

2021-10-25 10:33 UTC, Aliaksandrlosich commented on routes/auth.routes.js
> +          .json({ message: 'Такой пользователь уже существует' });
Месседжи все на англе, а на фронте уже на любой язык переводи

2021-10-25 10:33 UTC, Aliaksandrlosich commented on routes/auth.routes.js
> +      const hashePassword = await bcrypt.hash(password, 12); //шифрование пароля
Что за 12?

2021-10-25 10:43 UTC, SiarheiBalt commented on routes/auth.routes.js
> +      const hashePassword = await bcrypt.hash(password, 12); //шифрование пароля
Сложность шифрования

2021-10-28 08:51 UTC, Aliaksandrlosich commented on routes/auth.routes.js
> +      const hashePassword = await bcrypt.hash(password, 12); //шифрование пароля
Тогда стоит это выделить в понятную константу)

2021-11-02 07:10 UTC, Aliaksandrlosich approved these changes

2021-11-02 07:10 UTC, merged